// <auto-generated />
using System;
using AdminPanel.DataAccessLayer.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminPanel.DataAccessLayer.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20220603190020_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<double>("gunlukFiyat")
                        .HasColumnType("float");

                    b.Property<int>("kasaTipid")
                        .HasColumnType("int");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("markaid")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("tipid")
                        .HasColumnType("int");

                    b.Property<int>("uretimYili")
                        .HasColumnType("int");

                    b.Property<int>("vitesTipid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("kasaTipid");

                    b.HasIndex("markaid");

                    b.HasIndex("tipid");

                    b.HasIndex("vitesTipid");

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaKasaTip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("ArabaKasaTipleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaMarka", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("ArabaMarkalari");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaOzellik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("arabaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("arabaid");

                    b.ToTable("ArabaOzellikleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaTip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("ArabaTipleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaVitesTip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("ArabaVitesTipleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.ArabaBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("ArabaBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.GaleriBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("GaleriBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.HakkindaBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("HakkindaBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.HizmetBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("HizmetBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.IletisimBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("IletisimBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.IpucuVeYaziBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("IpucuVeYaziBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.PaketBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("PaketBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.PersonelBolumBilgisi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("altBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("PersonelBolumBilgileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("firmaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("iletisimid")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("firmaid");

                    b.HasIndex("iletisimid");

                    b.ToTable("Bayiler");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.BayiYonetici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("bayiid")
                        .HasColumnType("int");

                    b.Property<int>("firmaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("personelid")
                        .HasColumnType("int");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("bayiid");

                    b.HasIndex("firmaid");

                    b.HasIndex("personelid");

                    b.ToTable("BayiYoneticileri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("iletisimid")
                        .HasColumnType("int");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("iletisimid");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.FirmaSahip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("firmaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("personelid")
                        .HasColumnType("int");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("firmaid");

                    b.HasIndex("personelid");

                    b.ToTable("FirmaSahipleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HakkindaKismi.HakkindaIcerik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("resimURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("HakkindaIcerikleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HakkindaKismi.HakkindaReklam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("HakkindaReklamlar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.Hizmet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("hizmetid")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("hizmetid");

                    b.ToTable("HizmetAltlar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAltOzellik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("hizmetAltid")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("hizmetAltid");

                    b.ToTable("HizmetAltOzellikler");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Iletisimleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.IpucuKismi.IpucuVeYazi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("IpucuVeYazilar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.LogoKismi.SosyalMedyaLogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("SosyalMedyaLogolari");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MesajKismi.Mesaj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("konu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MusteriKismi.Musteri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("firmaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("id");

                    b.HasIndex("firmaid");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.Paket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Paketler");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketAitOzellik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("ozellikid")
                        .HasColumnType("int");

                    b.Property<int>("paketid")
                        .HasColumnType("int");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("ozellikid");

                    b.HasIndex("paketid");

                    b.ToTable("PaketAitOzellikleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketOzellik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("PaketOzellikleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelGorev", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("personelid")
                        .HasColumnType("int");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("personelid");

                    b.ToTable("PersonelGorevleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSifre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("personelid")
                        .HasColumnType("int");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("personelid");

                    b.ToTable("PersonelSifreleri");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSosyalMedya", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("guncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("personelid")
                        .HasColumnType("int");

                    b.Property<bool>("sil")
                        .HasColumnType("bit");

                    b.Property<DateTime>("silmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("sosyalMedyaLogoid")
                        .HasColumnType("int");

                    b.Property<string>("sosyalMedyaURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("personelid");

                    b.HasIndex("sosyalMedyaLogoid");

                    b.ToTable("PersonelSosyalMedyalari");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaKasaTip", "kasaTip")
                        .WithMany()
                        .HasForeignKey("kasaTipid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaMarka", "marka")
                        .WithMany()
                        .HasForeignKey("markaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaTip", "tip")
                        .WithMany()
                        .HasForeignKey("tipid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaVitesTip", "vitesTip")
                        .WithMany()
                        .HasForeignKey("vitesTipid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kasaTip");

                    b.Navigation("marka");

                    b.Navigation("tip");

                    b.Navigation("vitesTip");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaOzellik", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", "araba")
                        .WithMany()
                        .HasForeignKey("arabaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("araba");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("firmaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", "iletisim")
                        .WithMany()
                        .HasForeignKey("iletisimid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("firma");

                    b.Navigation("iletisim");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.BayiYonetici", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", "bayi")
                        .WithMany()
                        .HasForeignKey("bayiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("firmaid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("personelid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("bayi");

                    b.Navigation("firma");

                    b.Navigation("personel");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", "iletisim")
                        .WithMany()
                        .HasForeignKey("iletisimid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("iletisim");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.FirmaSahip", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("firmaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("personelid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("firma");

                    b.Navigation("personel");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.Hizmet", "hizmet")
                        .WithMany()
                        .HasForeignKey("hizmetid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hizmet");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAltOzellik", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", "hizmetAlt")
                        .WithMany()
                        .HasForeignKey("hizmetAltid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hizmetAlt");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MusteriKismi.Musteri", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("firmaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firma");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketAitOzellik", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketOzellik", "ozellik")
                        .WithMany()
                        .HasForeignKey("ozellikid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.Paket", "paket")
                        .WithMany()
                        .HasForeignKey("paketid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ozellik");

                    b.Navigation("paket");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelGorev", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("personelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personel");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSifre", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("personelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personel");
                });

            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSosyalMedya", b =>
                {
                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("personelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.LogoKismi.SosyalMedyaLogo", "sosyalMedyaLogo")
                        .WithMany()
                        .HasForeignKey("sosyalMedyaLogoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personel");

                    b.Navigation("sosyalMedyaLogo");
                });
#pragma warning restore 612, 618
        }
    }
}
